### ISSUE TITLE
It just buys a bunch of shit and doesn’t sell...

### ISSUE THREAD

**Issue by Scrut1ny** [Kurt212/TarkovTradeBot#6]
I set it up and ran it and all it did was buy buy buy really quick, but it didn't sell anything idk why. I didn't wanna lose anymore money so I stopped running it. Please tell me if I'm doing anything wrong lol.

**Comment by Kurt212** [comment]
lol

**Comment by Kurt212** [comment]
Hope next time you read your own code before running it!

Good luck :)
