### ISSUE TITLE
Where do i put this

### ISSUE THREAD

**Issue by Ninja6ix** [Kurt212/TarkovTradeBot#7]
Where do I place these files? not enough information on how to use

**Comment by Kurt212** [comment]
In fact, this is not a complete project, but kind of an example of how to build your own. I hoped to encourage other people to develop something awesome by showing them how I did it.

I controlled this particular bot from python console manually. Mostly for automatic buying cheap stuff to sell with a profit.

So I encourage you to read source code and try to learn something from it :)

Good luck!

P.S.
I'm no longer playing EFT. And I do not know mucn about current situation with Flea Market and its accessibility from the bot. But I hope that BSG also checked the source code and made reasonable conclusions.
